module.exports = {
  SKILL_LEARNED: "SKILL_LEARNED",
  PROJECT_CREATED: "PROJECT_CREATED",
  MILESTONE_APPROVED: "MILESTONE_APPROVED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  LEVEL_UP: "LEVEL_UP"
};
